//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccountAddress
    {
        public CustomerAccountAddress()
        {
            this.PolicySubscriptions = new HashSet<PolicySubscription>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string GUID { get; set; }
        public string BillingAddress { get; set; }
        public string BillingAddressAccountID { get; set; }
        public string CustomerAccountID { get; set; }
        public string BillingAddressContact { get; set; }
        public string BillingAddressNotes { get; set; }
    
        public virtual CustomerAccount CustomerAccount { get; set; }
        public virtual ICollection<PolicySubscription> PolicySubscriptions { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
