//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LinkwebEntities : DbContext
    {
        public LinkwebEntities()
            : base("name=LinkwebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerAccountAddress> CustomerAccountAddresses { get; set; }
        public virtual DbSet<CustomerAccount> CustomerAccounts { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MembershipPolicy> MembershipPolicies { get; set; }
        public virtual DbSet<OrganizationPolicy> OrganizationPolicies { get; set; }
        public virtual DbSet<PolicySubscription> PolicySubscriptions { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<SystemAccount> SystemAccounts { get; set; }
        public virtual DbSet<TransactionPayment> TransactionPayments { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<ServiceTypeCharge> ServiceTypeCharges { get; set; }
    }
}
