//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string GUID { get; set; }
        public string LogType { get; set; }
        public string LogDescription { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
