//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationPolicy
    {
        public string GUID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double VATPercentage { get; set; }
        public bool LimitAllowedSystemLogin { get; set; }
        public System.DateTime BeginAllowedTimeLogin { get; set; }
        public System.DateTime EndingAllowedTimeLogin { get; set; }
    }
}
