//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicySubscription
    {
        public string GUID { get; set; }
        public string PolicyGUID { get; set; }
        public string CustomerAccountAddressGUID { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public System.DateTime NextRenewalDate { get; set; }
        public System.DateTime NextMonthlyFeePaymentDate { get; set; }
    
        public virtual CustomerAccountAddress CustomerAccountAddress { get; set; }
        public virtual MembershipPolicy MembershipPolicy { get; set; }
    }
}
