//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public ServiceType()
        {
            this.Transactions = new HashSet<Transaction>();
            this.ServiceTypeCharges = new HashSet<ServiceTypeCharge>();
        }
    
        public string GUID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool AllowDelivery { get; set; }
        public bool AllowPickup { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<ServiceTypeCharge> ServiceTypeCharges { get; set; }
    }
}
