//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAccount
    {
        public string GUID { get; set; }
        public string Name { get; set; }
        public string LogonName { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public string HashedPassword { get; set; }
        public string AccountType { get; set; }
    }
}
