//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenSoft.Linkweb.Library.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionPayment
    {
        public string GUID { get; set; }
        public string TransactionID { get; set; }
        public string PaymentType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime DatePaid { get; set; }
        public string Notes { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
